//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiemTapHoa_WebNangCao.Models
{
    using System;
    using System.Collections.Generic;

    public partial class BangLuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangLuong()
        {
            this.NhanViens = new HashSet<NhanVien>();
            this.ChucVus = new HashSet<ChucVu>();
        }

        public BangLuong(int maBL, int? nhanVien, int thang, int nam, int soNgayNghi, int tongSoNgay, double? luong)
        {
            MaBL = maBL;
            MaNV = nhanVien;
            Thang = thang;
            Nam = nam;
            SoNgayNghi = soNgayNghi;
            TongSoNgay = tongSoNgay;
            Luong = luong;
        }
        public int MaBL { get; set; }
        public Nullable<int> MaNV { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<double> Luong { get; set; }
        public int SoNgayNghi { get; set; }
        public int TongSoNgay { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }

        public virtual NhanVien NhanVien { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<ChucVu> ChucVus { get; set; }
        public virtual ChucVu ChucVu { get; set; }
    }
}
