//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiemTapHoa_WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHD
    {
        public int MaHD { get; set; }
        public int MaHH { get; set; }
        public Nullable<double> SoLuong { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
