//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiemTapHoa_WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.BangLuongs = new HashSet<BangLuong>();
            this.HoaDons = new HashSet<HoaDon>();
        }

        public NhanVien(int maNV, string tenNV, DateTime? ngaySinh, string email, string sDT, string diaChi, string soTaiKhoan, int? chucVu, string gioiTinh, string hinhAnh)
        {
            MaNV = maNV;
            TenNV = tenNV;
            NgaySinh = ngaySinh;
            Email = email;
            SDT = sDT;
            DiaChi = diaChi;
            SoTaiKhoan = soTaiKhoan;
            ChucVu = chucVu;
            GioiTinh = gioiTinh;
            HinhAnh = hinhAnh;
        }

        public int MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string SoTaiKhoan { get; set; }
        public Nullable<int> ChucVu { get; set; }
        public string GioiTinh { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangLuong> BangLuongs { get; set; }
        public virtual ChucVu ChucVu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
