//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiemTapHoa_WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string TaiKhoan1 { get; set; }
        public string MatKhau { get; set; }
        public string LoaiTaiKhoan { get; set; }
        public string HinhAnh { get; set; }
    }
}
